version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  cooldown:
    minimum-age: 7
    semver:
      major: 30
      minor: 7
      patch: 3
  open-pull-requests-limit: 10
  groups:
    ruby-minor-and-patch:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  cooldown:
    minimum-age: 7
  open-pull-requests-limit: 5
  groups:
    github-actions-minor-and-patch:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
