default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  anki:
    <<: *default
    database: tmp/anki/collection.anki21
    migrations_paths: []

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  anki:
    <<: *default
    database: storage/anki-test.sqlite3
    migrations_paths: []

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  anki:
    <<: *default
    database: storage/production_collection.anki21
